// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package com.turing.rpc;

public interface HeartBeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
